AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: RSS Feed Fetcher


Parameters:
  FunctionName:
    Type: String
    Description: Name of the Lambda function
    Default: rss-feed-fetcher
    AllowedPattern: "[a-zA-Z0-9-_]+"
    ConstraintDescription: must contain only alphanumeric characters, dashes, and underscores.

  TriggerName:
    Type: String
    Description: Name of the trigger
    Default: rss-feed-fetcher-trigger
    AllowedPattern: "[a-zA-Z0-9-_]+"
    ConstraintDescription: must contain only alphanumeric characters, dashes, and underscores.

  TriggerDescription:
    Type: String
    Description: Description of the trigger
    Default: Triggers the RSS feed fetcher Lambda function


  LambdaDescription:
    Type: String
    Description: Description of the Lambda function
    Default: Fetches RSS feeds and sends them to the meme processing queue


Resources:
  ScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: dist/lambda.handler
      Runtime: nodejs18.x
      Description: !Ref LambdaDescription
      MemorySize: 256
      Timeout: 20
      CodeUri: ./dist
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - sqs:SendMessage
                - events:PutEvents
              Resource:
                - '*'

  ScraperTrigger:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Name: !Ref TriggerName
      Description: !Ref TriggerDescription
      ScheduleExpression: rate(3 hours)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ScraperFunction.Arn
          Id: !Ref FunctionName


  ScraperInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt ScraperFunction.Arn
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt ScraperTrigger.Arn
